// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:7be1d1f2-75ad-41db-8c93-00805c218061",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_tu5PKILor",
    "aws_user_pools_web_client_id": "23tlqnd9vqp4u18pu557jipvr9",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://wjishtf64zc2hplhdx5ow5w7me.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
